create table if not exists public.users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  matcha_blurb text,
  coffee_blurb text,
  tags jsonb not null default '[]'::jsonb,
  embeddings jsonb,
  seen jsonb not null default '[]'::jsonb,
  liked_events jsonb not null default '[]'::jsonb
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text,
  description text,
  tags jsonb not null default '[]'::jsonb,
  matcha_mode boolean not null default true,
  embeddings jsonb,
  image_link text
);

create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint references public.users(id) on delete cascade,
  event_id bigint references public.events(id) on delete cascade,
  time_spent double precision,
  liked boolean,
  matcha_mode boolean
);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.users to anon, authenticated, service_role;
grant select, insert, update, delete on public.events to anon, authenticated, service_role;
grant select, insert, update, delete on public.analytics to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
